export default 
	[ // 模拟接口返回的数据结构
    {   
        id:1,
        Type:"Inductive proximity switch",
        Category:"DC 3-wire M12 inductive proximity switch",
        Environment: "Normal",
        Image:"",
        Diagram:"",
        Dimension:"M12", 
        Length:22,
        Type:"Flush",
        Sn:2mm,
        Material:"Nickel-plated copper",
        FacingMaterial:"POM",
        OperatingVoltage:"10-30VDC",
        AllowableRippleVoltage: "<10%",
        NoLoadCurrent: "<10mA",
        MaxiumLoadCurrent: "200mA",
        LeakedCurrent: "<0.01mA",
        VoltageDrop: "<2.0V",
        SwitchFrequency: "2KHZ",
        ResponseTime: "0.1ms/0.1ms",
        Hysteresis: "<15%(Sr)",
        RepeatAccuracy: "<1.0%(Sr)",
        IPLevel: "IP67",
        OperatingTemperature: "-25℃-+70℃",
        TemperatureDrift: "<10%(Sr)",
        Protection: "short circuit protection",
        OverloadCurrent: "220mA",
        Output:"NPN NO", 
        Connector:"axial cable exit",
        ItemNumber: "HS-C12-N01",
        Indicator:"Yes",
        Price:212
    },
    {
        id:2,
        Type:"Inductive proximity switch",
        Category:"DC 3-wire M12 inductive proximity switch",
        Environment: "Normal",
        Image:"",
        Diagram:"",
        Dimension:"M12", 
        Length:22,
        Type:"Flush",
        Sn:2mm,
        Material:"Nickel-plated copper",
        FacingMaterial:"POM",
        OperatingVoltage:"10-30VDC",
        AllowableRippleVoltage: "<10%",
        NoLoadCurrent: "<10mA",
        MaxiumLoadCurrent: "200mA",
        LeakedCurrent: "<0.01mA",
        VoltageDrop: "<2.0V",
        SwitchFrequency: "2KHZ",
        ResponseTime: "0.1ms/0.1ms",
        Hysterisis: "<15%(Sr)",
        RepeatAccuracy: "<1.0%(Sr)",
        IPLevel: "IP67",
        OperatingTemperature: "-25℃-+70℃",
        TemperatureDrift: "<10%(Sr)",
        Protection: "short circuit protection",
        OverloadCurrent: "220mA",
        Output:"NPN NO", 
        Connector:"axial cable exit",
        ItemNumber: "HS-C12-N01",
        Indicator:"Yes",
        Price:212

    }
]